ScrumTracker/WebSite/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Contracts.Interfaces;
using DTO.Entities;
using PagedList;
using WebSite.Models;
using WebSite.Models.Team;
using WebSite.Util.Filters;

namespace WebSite.Controllers
{
    [Authorize]
    public class TeamController : BaseController
    {
        private readonly IManagerUser _userManager;
        private readonly IManagerTeam _teamManager;
        private readonly IManagerUserTeamPos _userTeamPosManager;
        private readonly IManagerPosition _positionManager;
        private readonly IManagerProject _projectManager;

        public TeamController(IManagerUser userManager, IManagerTeam teamManager, IManagerUserTeamPos userTeamPosManager,
            IManagerPosition positionManager, IManagerProject projectManager)
        {
            _positionManager = positionManager;
            _userManager = userManager;
            _teamManager = teamManager;
            _userTeamPosManager = userTeamPosManager;
            _projectManager = projectManager;
        }
        
        public ActionResult Index(Guid? id)
        {
            ViewBag.ProjectId = id;  // for assign team to project
            var users = _userManager.GetAllUsersByDepartment(CurrentUser.DepartmentId).OrderBy(x => x.Email).ToPagedList(1, 6);
            var teams = _teamManager.GetAllTeamsByDepartment(CurrentUser.DepartmentId).OrderByDescending(x => x.DateCreated).ToPagedList(1, 6);
            var userTeamPositions = new List<UserTeamPositionDto>().ToPagedList(1, 6);
            TeamModel model = new TeamModel() { Users = users, Teams = teams, UserTeamPositions = userTeamPositions };
            ViewBag.IsUserAdmin = HttpContext.User.IsInRole("Admin");
            return View(model);
        }

        public ActionResult ShowTeam(Guid? id)
        {
            var users = _userManager.GetAllUsersByDepartment(CurrentUser.DepartmentId).OrderBy(x => x.Email).ToPagedList(1, 6);
            var teams = _teamManager.GetAllTeamsByDepartment(CurrentUser.DepartmentId).Where(x => x.Id == id).OrderByDescending(x => x.DateCreated).ToPagedList(1, 6);
            var userTeamPositions = _userTeamPosManager.GetAllUserTeamPos().Where(x => x.TeamId == id).OrderBy(x => x.User.Email).ToPagedList(1, 6);
            TeamModel model = new TeamModel() { Users = users, Teams = teams, UserTeamPositions = userTeamPositions };
            ViewBag.Positions = new SelectList(_positionManager.GetAllPositions(), "Id", "Name");
            ViewBag.AccessToEditTeam = HttpContext.User.IsInRole("Admin"); 
            ViewBag.IsUserAdmin = HttpContext.User.IsInRole("Admin");
            return View("Index", model);
        }

        [TeamAction]
        public ActionResult GetUserTeamPostions(string id)
        {
            //var userTeamPos =_userTeamPosManager.GetUsersTeamPosByTeamIdAndUserId(new Guid(id), CurrentUserId);
            //var positionName = userTeamPos?.Position?.Name;
            //var isAdmin = HttpContext.User.IsInRole("Admin");


            var userTeamPositions = _userTeamPosManager.GetUsersTeamPosByTeamId(new Guid(id)).OrderBy(x => x.User.Email).ToPagedList(1, 6);
            TeamModel model = new TeamModel() { UserTeamPositions = userTeamPositions };
            ViewBag.Positions = new SelectList(_positionManager.GetAllPositions(), "Id", "Name");

            //if (isAdmin || positionName == "Project Manager")
            //{
            //    ViewBag.UserPermission = true;
            //    ViewBag.TeamPmId = CurrentUserId;
            //    ViewBag.IsUserAdmin = isAdmin;
            //}
            //else
            //{
            //    ViewBag.UserPermission = false;
            //    ViewBag.TeamPmId = null;
            //}
            //var test = ViewBag.TeamPmId??"22";
            //Debug.WriteLine(test);
           

            return PartialView("~/Views/Team/_ListUsersTeamPosPartial.cshtml", model);
        }
        [TeamAction(Access = true)]

        public ActionResult AddUserToTeam(string userId, string teamId)
        {
            OperationStatus operationStatus = new OperationStatus();
            var userTeamPosition = _userTeamPosManager.GetUsersTeamPosByTeamIdAndUserId(new Guid(teamId),userId);
            if (userTeamPosition == null)
            {
                userTeamPosition = new UserTeamPositionDto() { UserId = userId, TeamId = new Guid(teamId) };
                _userTeamPosManager.AddUserTeamPos(userTeamPosition);
                operationStatus.Status = true;
                if (userTeamPosition.TeamId != null) operationStatus.InsertedId = (Guid)userTeamPosition.TeamId;
            }
            return Json(operationStatus, JsonRequestBehavior.AllowGet);

        }

        public ActionResult AutocompleteTeamSearch(string term)
        {
            var model = _teamManager.GetAllTeamsByDepartment(CurrentUser.DepartmentId).Where(x => x.Name.Contains(term)).OrderByDescending(x => x.DateCreated)
                .Select(x => new { value = x.Name })
                .Distinct();
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetTeams(string term, int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            var teams = _teamManager.GetAllTeamsByDepartment(CurrentUser.DepartmentId).OrderByDescending(x => x.DateCreated).ToPagedList(pageNumber, pageSize);

            TeamModel model = new TeamModel() { Teams = teams };
            return PartialView("~/Views/Team/_ListTeamsPartial.cshtml", model);
        }
        public ActionResult SearchTeams(string term, int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            IPagedList<TeamDto> teams;
            if (term != null)
                teams = _teamManager.GetAllTeamsByDepartment(CurrentUser.DepartmentId).Where(a => a.Name.Contains(term)).OrderByDescending(x => x.DateCreated).ToPagedList(pageNumber, pageSize);
            else
            {
                teams = _teamManager.GetAllTeamsByDepartment(CurrentUser.DepartmentId).OrderByDescending(x => x.DateCreated).ToPagedList(pageNumber, pageSize);
            }
            ViewBag.IsUserAdmin = HttpContext.User.IsInRole("Admin");
            ViewBag.TeamFilter = term;
            ViewBag.TeamPage = pageNumber;

            TeamModel model = new TeamModel() { Teams = teams };
            return PartialView("~/Views/Team/_ListTeamsPartial.cshtml", model);
        }


        public ActionResult AutocompleteUserSearch(string term)
        {
            var model = _userManager.GetAllUsersByDepartment(CurrentUser.DepartmentId).Where(x => x.Email.Contains(term)).OrderBy(x => x.Email)
                .Select(x => new { value = x.Email })
                .Distinct();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SearchUsers(string term, string teamId, int? page)
        {
            var teamUsers = new List<UserDto>();
            if (teamId != null)
            {
                teamUsers = _teamManager.GetTeamById(new Guid(teamId)).UserTeamPositions.Select(x => x.User).ToList();
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            var availableUsers  = _userManager.GetAllUsersByDepartment(CurrentUser.DepartmentId).Except(teamUsers);
            IPagedList<UserDto> users;
            if (term != null)
                users = availableUsers.Where(a => a.Email.Contains(term)).OrderBy(x => x.Email).ToPagedList(pageNumber, pageSize);
            else
            {
                users = availableUsers.OrderBy(x => x.Email).ToPagedList(pageNumber, pageSize);
            }
            ViewBag.UserFilter = term;
            ViewBag.UserPage = pageNumber;
            ViewBag.TeamIdFilter = teamId;
            TeamModel model = new TeamModel() { Users = users };
            
            return PartialView("~/Views/Team/_ListUsersPartial.cshtml", model);
        }
        
        public ActionResult EditTeamInfo(string id)
        {
            var team = _teamManager.GetTeamById(new Guid(id));

            EditTeamModel model = new EditTeamModel() { Id = team.Id, Name = team.Name, Description = team.Description };
            return PartialView("~/Views/Team/_EditTeamModalPartial.cshtml", model);
        }
        
        public ActionResult EditTeam(EditTeamModel model)
        {
            OperationStatus operationStatus = new OperationStatus();
            if (ModelState.IsValid)
            {
                var team = _teamManager.GetTeamById(model.Id);
                team.Name = model.Name;
                team.Description = model.Description;
                _teamManager.UpdateTeam(team);
                operationStatus.Status = true;
            }
            else
            {
                operationStatus.Status = false;
                operationStatus.Message = "Something wrong";
            }
            return Json(operationStatus, JsonRequestBehavior.AllowGet);
        }
        [TeamAction]
        public ActionResult DeleteTeamInfo(string id)
        {
            var team = _teamManager.GetAllTeamsByDepartment(CurrentUser.DepartmentId).First(x => x.Id == new Guid(id));
            DeleteTeamModel model = new DeleteTeamModel() { Id = team.Id };
            return PartialView("~/Views/Team/_DeleteTeamModalPartial.cshtml", model);
        }

        public ActionResult DeleteTeam(DeleteTeamModel model)
        {
            OperationStatus operationStatus = new OperationStatus();
            var team = _teamManager.GetTeamById(model.Id);
            if (team != null)
            {
                _teamManager.RemoveTeam(team);
                operationStatus.Status = true;
            }
            return Json(operationStatus, JsonRequestBehavior.AllowGet);
        }
        [TeamAction]

ScrumTracker/WebSite/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/css/empty")
</head>
<body>
    <div class="empty-body">
        <noscript>
            <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>This site requires Javascript to be enabled!</strong>
            </div>
        </noscript>
        <div class="container body-content">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/Scripts/empty")
    @Scripts.Render("~/bundles/jqueryval")
   
</body>
</html>

ScrumTracker/WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='@Url.Content("~/Content/themes/base/all.css")' rel="stylesheet" type="text/css" />
    @Styles.Render("~/css/bootstrap")
    @Styles.Render("~/css/main")

</head>
<body>
    <div class="navbar navbar-default  ">
        <div class="container">

            <div class="navbar-header">
                <div>
                    <a href="@Url.Action("Index", "Home", new {area = ""})">
                        <img src="~/Content/images/logo.png" width="225" style="float: left; margin: 3px 10px 0 0;"/>
                    </a>
                    @*@Html.ActionLink("SCRUMTRACKER", "Index", "Home", new { area = "" }, new { @class = "navbar-brand", style= "text-shadow: none;" })*@
                </div>
            </div>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar">54645</span>
                <span class="icon-bar">5646</span>
                <span class="icon-bar"></span>
            </button>

            <ul class="nav navbar-nav ">
                <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                <li>@Html.ActionLink(Resources.Resource.Projects, "Index", "Project")</li>
                <li>@Html.ActionLink(Resources.Resource.Sprints, "Index", "Sprint")</li>
                <li>@Html.ActionLink(Resources.Resource.Issues, "Index", "Issue")</li>
                <li>@Html.ActionLink(Resources.Resource.Teams, "Index", "Team")</li>
            </ul>
            @Html.Partial("_LoginPartial")

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav"></ul>
        </div>
    </div>

    <noscript>
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>This site requires Javascript to be enabled!</strong>
        </div>
    </noscript>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer>
        </footer>
    @Scripts.Render("~/Scripts/basic")
    @RenderSection("scripts", false)
</body>
</html>

ScrumTracker/WebSite/Views/Shared/_SingleComment.cshtml
@model WebSite.Models.Issue.CommentViewModel
<li>
    <div class="commenter-avatar"><img src=@Url.Content($"/Content/images/avatars/{Model.Avatar}") alt="avatar" /></div>
    <div class="commenter-name">@Model.FirstName @Model.LastName</div>
    <div class="comment-date">@Model.Date</div>
    <div class="clearfix"></div>
    <div class="comment-text">@Model.Comment</div>
</li>