ScrumTracker/WebSite/Models/Issue/AddIssueModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO.Entities;
using Resources;

namespace WebSite.Models.Issue
{
    public class AddIssueModel
    {
        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "ValidationNameRequired")]
        [StringLength(100, ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "ValidationNameLength", MinimumLength = 6)]
        [Display(ResourceType = typeof(Resource), Name = "Name")]
        public string Name { get; set; }

        //[Required(ErrorMessage = "Description is required field")]
        //[StringLength(50, MinimumLength = 3, ErrorMessage = "Description length must be min 3 characters")]
        [Display(ResourceType = typeof(Resource), Name = "Description")]
        public string Description { get; set; }

        public Guid? ProjectId { get; set; }
        public Guid? SprintId { get; set; }
        public Guid? IssueTypeId { get; set; }
        public Guid? ParentIssueId { get; set; }
    }
}

ScrumTracker/WebSite/Models/Issue/DeleteIssueModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebSite.Models.Issue
{
    public class DeleteIssueModel
    {
        public Guid Id { get; set; }
    }
}

ScrumTracker/WebSite/Models/Issue/IssueInfoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using DTO.Entities;

namespace WebSite.Models.Issue
{
    public class IssueInfoModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateCreate { get; set; }
        public Guid? StateId { get; set; }
        public Guid? PriorityId { get; set; }
        public Guid? SprintId { get; set; }
        public Guid? IssueTypeId { get; set; }
        public Guid? ProjectId { get; set; }
        public string CreatorId { get; set; }
        public string AssigneeId { get; set; }
        public int? Estimate { get; set; }
        public int? SpentTime {
            get
            {
                if(TimeTrackings!= null && TimeTrackings.Any())
                return TimeTrackings.Sum(x => x.SpentTime);
                return 0;
            }
        }
        public int Number { get; set; }
        public Guid? ParentIssueId { get; set; }
        //public virtual ICollection<HistoryDto> Histories { get; set; }
        public IssuePriorityDto Priority { get; set; }
        public IssueStateDto State { get; set; }
        public UserDto Creator { get; set; }
        public UserDto Assignee { get; set; }
        public IssueDto ParentIssue { get; set; }
        public IssueTypeDto IssueType { get; set; }
        public SprintDto Sprint { get; set; }
        public ProjectDto Project { get; set; }
        public int CountIssues { get; set; }
        public ICollection<IssueDto> Children { get; set; }
        public string Key;
        public IEnumerable<CommentDto> CommentsList { get; set; }
        public ICollection<TimeTrackingDto> TimeTrackings { get; set; }

    }
    public class CommentViewModel
    {
        public string Avatar { get; set; }
        public string CommmentId { get; set; }
        public DateTime Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Comment { get; set; }
        public Guid IssueId { get; set; }


    }
}

ScrumTracker/WebSite/Models/Issue/IssueModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DTO.Entities;
using PagedList;

namespace WebSite.Models.Issue
{
    public class IssueModel
    {
        public IPagedList<IssueDto> Issues { get; set; }
        public Guid? SelectedProjectId { get; set; }
    }
}

ScrumTracker/WebSite/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Contracts.Interfaces;
using DTO.Entities;
using PagedList;
using WebSite.Models;
using WebSite.Models.Issue;
using WebSite.Util;
using WebSite.Util.Filters;

namespace WebSite.Controllers
{
    [Authorize]
    public class IssueController : BaseController
    {
        private readonly IManagerIssue _issueManager;
        private readonly IManagerProject _projectManager;
        private readonly IManagerTeam _teamManager;
        private readonly IManagerComment _commentManager;
        private readonly IssuesFilter _issueFilter;

        public IssueController(IManagerIssue issueManager, IManagerProject projectManager, IManagerTeam teamManager,IManagerComment commentManager)
        {
            _issueFilter = new IssuesFilter(CurrentUserId);
            _issueManager = issueManager;
            _projectManager = projectManager;
            _teamManager = teamManager;
            _commentManager = commentManager;
        }

        // GET: Issue
        public ActionResult Index(Guid? id, Guid? issueId, Guid? sprintId, string stateName)
        {
            var projects = _projectManager.GetProjectByDepartmentId(CurrentUser.Department.Id);
            var model = new IssueModel() { Issues = new List<IssueDto>().ToPagedList(1, 7) };
            if (projects == null) return View(model);
            //var dtos = projects as ProjectDto[] ?? projects.ToArray();
            var projectDtos = projects as IList<ProjectDto> ?? projects.ToList();
            Guid? projectId = id ?? projectDtos.First().Id;
            ViewBag.Projects = new SelectList(projectDtos, "Id", "Name", projectId);
            IEnumerable<IssueDto> issues;
            if (issueId == null)
            {

                issues =
                    _issueManager.GetAllIssues()
                        .Where(x => x.ProjectId == projectId)
                        .OrderByDescending(x => x.DateCreate);
                if (sprintId != null)
                {
                    issues = _issueFilter.Execute(issues, sprintId,stateName);
                }
            }
           
            else
            {
                var issue = _issueManager.GetIssueById(issueId);
                issues = new List<IssueDto> {issue};
                ViewBag.IssueFilter = issue.Name;
            }
            model.Issues = issues.ToPagedList(1,7);
            ViewBag.ProjectId = projectId;
            Permission(projectDtos.First());
            return View(model);
        }

        private void Permission(ProjectDto project)
        {
            ViewBag.Permission = false;
            UserTeamPositionDto userTeamPos = null;

            if (project.Team?.UserTeamPositions != null)
                userTeamPos = project.Team.UserTeamPositions.FirstOrDefault(x => x.UserId == CurrentUserId);
            if (HttpContext.User.IsInRole(Resources.Resource.Admin) || userTeamPos != null)
            {
                ViewBag.Permission = true;
            }
        }
        public ActionResult AddIssue(AddIssueModel model)
        {
            var test = HttpContext.Request.Form;
            OperationStatus operationStatus = new OperationStatus();
            var type = _issueManager.GetTypeByName("Task");
            var priority = _issueManager.GetPriorityByName("Normal");
            var state = _issueManager.GetStateByName("Open");
            var issues = _issueManager.GetAllIssuesByProjectId(model.ProjectId).ToList();
            int maxNumber;
            if(issues.Count > 0)
                maxNumber = issues.Max(x => x.Number)+1;
            else
            {
                maxNumber = 1;
            }
           IssueDto issue = new IssueDto()
            {
                Name = model.Name,
                Description = model.Description,
                DateCreate = DateTime.Now,
                ProjectId = model.ProjectId,
                StateId = state.Id,
                PriorityId = priority.Id,
                IssueTypeId = type.Id,
                Number = maxNumber
            };
            _issueManager.AddIssue(issue);
            operationStatus.Status = true;
            return Json(operationStatus, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddIssueInfo(string id)
        {
            AddIssueModel model = new AddIssueModel() { ProjectId = new Guid(id) };
            return PartialView("~/Views/Issue/_AddIssueModalPartial.cshtml", model);
        }

        public ActionResult DeleteIssueInfo(string id)
        {
            var issue = _issueManager.GetAllIssues().First(x => x.Id == new Guid(id));
            DeleteIssueModel model = new DeleteIssueModel() { Id = issue.Id };
            return PartialView("~/Views/Issue/_DeleteIssueModalPartial.cshtml", model);
        }

        public ActionResult DeleteIssue(DeleteIssueModel model)
        {
            OperationStatus operationStatus = new OperationStatus();
            var issue = _issueManager.GetAllIssues().First(x => x.Id == model.Id);
            if (issue != null)
            {
                //if (issue.TimeTrackings != null)
                //{
                //    _issueManager.RemoveTimeTracking(issue.TimeTrackings);
                //    issue.TimeTrackings = null;
                //}
                _issueManager.RemoveIssue(issue);
                operationStatus.Status = true;
            }
            return Json(operationStatus, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SearchIssues(string term, int? page, string projectId, string sortFilter, Guid? issueId)
        {
            int pageSize = 7;
            int pageNumber = (page ?? 1);
            IEnumerable<IssueDto> issues;
            if (term != null)
                issues =
                    _issueManager.GetAllIssues()
                        .Where(a => a.ProjectId == new Guid(projectId) && a.Name.Contains(term))
                        .OrderByDescending(x => x.DateCreate);
            else
            {
                issues = _issueManager.GetAllIssues().Where(a => a.ProjectId == new Guid(projectId)).OrderByDescending(x => x.DateCreate);
            }
            //switch (sortFilter)
            //{
            //    case "open":
            //        issues = issues.Where(x => x.State == _issueManager.GetStateByName("Open"));
            //        break;
            //    case "my":
            //        issues = issues.Where(x => x.AssigneeId == CurrentUserId);
            //        break;
            //    case "in-progress":
            //        issues = issues.Where(x => x.State == _issueManager.GetStateByName("In Progress"));
            //        break;
            //}
            if (!string.IsNullOrEmpty(sortFilter))
            {
               issues = _issueFilter.Execute(issues,null, sortFilter);
            }
            Permission(_projectManager.GetProjectById(new Guid(projectId)));
            ViewBag.IssueFilter = term;
            ViewBag.IssuePage = pageNumber;
            ViewBag.ProjectId = projectId;
            ViewBag.IssueSortFilter = sortFilter;
            IssueModel model = new IssueModel() { Issues = issues.ToPagedList(pageNumber,pageSize) };
            return PartialView("~/Views/Issue/_ListIssuesPartial.cshtml", model);
        }

        
        public ActionResult AutocompleteIssueSearch(string term)
        {
            var model = _issueManager.GetAllIssues().Where(x => x.Name.Contains(term)).OrderBy(x => x.Name)
                .Select(x => new { value = x.Name })
                .Distinct();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IssueInfo(Guid? id)
        {
            ViewBag.IssuePriorities = new SelectList(_issueManager.GetAllIssuePriorities(), "Id", "Name");
            ViewBag.IssueTypes = new SelectList(_issueManager.GetAllIssueTypes(), "Id", "Name");

            ViewBag.IssueStates = new SelectList(_issueManager.GetAllIssueStates(), "Id", "Name");

            ViewBag.TimeTrackingTypes = new SelectList(_issueManager.GetAllTimeTrackingTypes(), "Id", "Name");

            var issue = _issueManager.GetIssueById(id);
            var projectId = issue.ProjectId;
            var teamId = _projectManager.GetProjectById(projectId).TeamId;
            var team = _teamManager.GetTeamById(teamId);
            IEnumerable<UserDto> usersAsignee = new List<UserDto>();
            if (team != null)
                usersAsignee = team.UserTeamPositions.Select(x => x.User);

            IssueInfoModel model = AutoMapperConfig.IssueDtoToIssueModelInfo(issue);
            ViewBag.IssueAsignee = model.AssigneeId != null
                ? new SelectList(usersAsignee, "Id", "Email", model.AssigneeId)
                : new SelectList(usersAsignee, "Id", "Email");
            ViewBag.IssuePriorities = model.PriorityId != null
                ? new SelectList(_issueManager.GetAllIssuePriorities(), "Id", "Name",
                    model.PriorityId)
                : new SelectList(_issueManager.GetAllIssuePriorities(), "Id", "Name");
            ViewBag.IssueTypes = model.IssueTypeId != null
                ? new SelectList(_issueManager.GetAllIssueTypes(), "Id", "Name", model.IssueTypeId)
                : new SelectList(_issueManager.GetAllIssueTypes(), "Id", "Name");
            ViewBag.IssueStates = model.StateId != null
                ? ViewBag.IssueStates = new SelectList(_issueManager.GetAllIssueStates(), "Id", "Name", model.StateId)
                : ViewBag.IssueStates = new SelectList(_issueManager.GetAllIssueStates(), "Id", "Name");

            var comments = _commentManager.GetAll().Where(c=>c.IssueId==issue.Id);
            model.CommentsList = comments;
            Permission(issue.Project);
            return PartialView("~/Views/Issue/_IssueInfoPartial.cshtml", model);
        }

        [HttpPost]

ScrumTracker/WebSite/Views/Issue/Index.cshtml
@using WebSite.Models.Issue
@model WebSite.Models.Issue.IssueModel
@{
    ViewBag.Title = "Index";
}

<div class="row issue-top-menu">
    <div class="col-md-1">
        <i id="show-issue-menu" class="fa fa-align-justify"></i>
    </div>
    @if (ViewBag.Projects != null)
    {
        <div class="col-md-1">
            <span>@Resources.Resource.IssueProject:</span>
        </div>
        <div class="col-md-8">
            @Html.DropDownListFor(m => m.SelectedProjectId, ViewBag.Projects as SelectList, null, new {@class = "selected-issue-project"})

        </div>
    }
    else
    {
        <div class="col-md-9">@Resources.Resource.NoProjects</div>
    }
    <div class="col-md-2">
        @Html.Hidden("AddIssueInfo", Url.Action("AddIssueInfo"))
        <div class="pull-right">
            @if (ViewBag.Projects != null && ViewBag.Permission)
            {
                <button class="btn issueBtn issue-add">@Resources.Resource.CreateIssueBtn</button>
            }
        </div>
    </div>
</div>
<div class="issue-slide-menu">
    <h4>@Resources.Resource.Filters:</h4>
    <ul class="issue-sort-filters">
        <li data-sort="my">@Resources.Resource.IssueFilterMy</li>
        <li data-sort="all">@Resources.Resource.IssueFilterAll</li>
        <li data-sort="open">@Resources.Resource.IssueFilterOpen</li>
        <li data-sort="in-progress">@Resources.Resource.IssueFilterInProgress</li>
    </ul>
</div>
<div class="issue-content">
    <div class="issues">
        <div class="text-center"> <input type="text" id="search-issue-input" placeholder="Enter search issue request" data-autocomplete-source='@Url.Action("AutocompleteIssueSearch", "Issue")' /></div>
        @Html.Hidden("GetIssuesByTerm", Url.Action("SearchIssues"))
        <div id="issues">  @Html.Partial("~/Views/Issue/_ListIssuesPartial.cshtml")</div>
    </div>
    <div class="issue-info">
        @Html.Hidden("GetIssueInfo", Url.Action("IssueInfo"))
        <div id="issue-info">
        </div>
    </div>
</div>


<div id="modAddIssueDialog" class="modal fade">
    <div id="dialogAddIssueContent" class="modal-dialog">
        @*@Html.Partial("~/Views/Issue/_AddIssueModalPartial.cshtml", new AddIssueModel())*@
    </div>
</div>

<div id="modDeleteIssueDialog" class="modal fade">
    <div id="dialogDeleteIssueContent" class="modal-dialog"></div>
</div>
<div id="modAddRelativeIssueDialog" class="modal fade">
    <div id="dialogRelativeIssueContent" class="modal-dialog"></div>
</div>

@section scripts
{
    <script type="text/javascript">
        function PostComment(element) {

            var commentValue = $("#userComment").val();

            if (commentValue != "") {

                var url = '@Url.Action("CreateComment","Issue")';
                var isueid = $("#Id").val();

                $.post(url,
                {
                    text: commentValue,
                    issueId: isueid
                }).success(function (data) {
                    $("#userComment").val('');
                    $(".no-comments").remove();
                    $(".comments-list").append(data);
                }).fail(function (data) {
                    console.log(data);
                    alert("Error while addig comment");
                });
            } else {
               
            }
        }


    </script>
    
}

ScrumTracker/WebSite/Views/Issue/ListIssuesTreeViewPartial.cshtml
@using PagedList
@using PagedList.Mvc
@model WebSite.Models.Issue.IssueModel
@{
    ViewBag.Title = "_ListIssuesPartial";
}

<ul id="issue-list">
    <div class="row headings-for-issues">
        <h5 class="col-md-3">Priority</h5>
        <h5 class="col-md-3">State</h5>
        <h5 class="col-md-2">Type</h5>
        <h5 class="col-md-2">Sprint</h5>
    </div>
    @foreach (var issue in Model.Issues)
    {
    <li class="issue-item">
        <p class="issue-list-item-name">
            <a href="#" data-id="@issue.Id" type="button">@issue.Name</a>
        </p>
        <div class="row issue-list-item-info">
            <div class="col-md-3"> @Html.DisplayFor(model => issue.Priority.Name) </div>
            <div class="col-md-3"> @Html.DisplayFor(model => issue.State.Name) </div>
            <div class="col-md-2"> @Html.DisplayFor(model => issue.IssueType.Name) </div>
            <div class="col-md-2">
                @if (issue.Sprint != null)
                {
                @Html.DisplayFor(model => issue.Sprint.Name)
                }
                else
                {
                <p>Unkown</p>
                }
            </div>
            <div class="col-md-1">
                <div class="delete-issue">
                    <a href="@Url.Action("DeleteIssueInfo", "Issue", new {id = issue.Id})" class="issue-delete"><i class="fa  fa-times"></i></a>
                </div>
            </div>
        </div>
        <input type="hidden" class="issue-id" value="@issue.Id" />
        @if (issue.Children != null)
        {
        <ul>
            @foreach (var child in issue.Children)
            {
                <li>@child.Name</li>
            }
        </ul>
        }
    </li>
    }
</ul>



<input type="hidden" value="@ViewBag.IssueFilter" id="viewbagIssueFilter" />
<input type="hidden" value="@ViewBag.IssuePage" id="viewbagIssuePage" />
<input type="hidden" value="@ViewBag.ProjectId" id="viewbagIssueProject" />


<div class="text-center">
    @if (Model.Issues.PageCount > 1)
    {
    @Html.PagedListPager((IPagedList)Model.Issues,
        page => Url.Action("SearchIssues", new
        {
            page,
            term = ViewBag.IssueFilter,
            projectId = ViewBag.ProjectId
        }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.PageNumbersOnly,
            new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "Get",
                UpdateTargetId = "issues"
            }))

    }
</div>

ScrumTracker/WebSite/Views/Issue/_AddIssueModalPartial.cshtml
@model WebSite.Models.Issue.AddIssueModel
@{
    ViewBag.Title = "_AddIssueModalPartial";
}

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">&times;</button>
        <h4>@Resources.Resource.IssueAdd</h4>
    </div>
    <div class="modal-body">
        <div id="addIssueError"></div>
        @using (Html.BeginForm("AddIssue", "Issue", FormMethod.Post, new { Id = "AddIssueForm" }))
        {
        @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.ProjectId)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })

            @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "Description" })
            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })

            <div class="row addIssueButtons">
                <div class="col-md-6 text-center">
                    <button class="btn btn-primary">@Resources.Resource.Save</button>
                </div>
                <div class="col-md-6 text-center">
                    <button class="btn btn-primary" data-dismiss="modal" area-hidden="true">@Resources.Resource.Cancel</button>
                </div>
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $.validator.unobtrusive.parse($("form"));
</script>

ScrumTracker/WebSite/Views/Issue/_DeleteIssueModalPartial.cshtml
@model WebSite.Models.Issue.DeleteIssueModel
@{
    ViewBag.Title = "_DeleteIssueModelPartial";
}

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">&times;</button>
        <h4>@Resources.Resource.DeleteConfirm</h4>
    </div>
    <div class="modal-body">
        @Html.HiddenFor(x => x.Id, new { @class = "issueIdForDelete" })
        <div class="row">
            <div class="col-md-6 text-center">
                <button id="btnConfirmDeleteIssue" class="btn btn-primary">OK</button>
                @Html.Hidden("deleteIssue", Url.Action("DeleteIssue"))
            </div>
            <div class="col-md-6 text-center">
                <button class="btn btn-primary" data-dismiss="modal" area-hidden="true">@Resources.Resource.Cancel</button>
            </div>
        </div>
    </div>
</div>

ScrumTracker/WebSite/Views/Issue/_IssueCommentsPartial.cshtml
@model WebSite.Models.Issue.IssueInfoModel
    @using Resources
@{
    ViewBag.Title = "_IssueCommentsPartial";
}

<div class="panel-heading">
    <h3 class="panel-title">@Resource.CommentsTitle</h3>
    <div class="input-group">
        <input type="text" id="userComment" class="form-control input-sm chat-input" placeholder="@Resource.TextComments" />
        <span class="input-group-btn" onclick="PostComment()">
            <a href="#" class="btn btn-success btn-sm" onclick="event.preventDefault()">@Resource.AddComment</a>
        </span>

    </div>
    <div class="comments-area" style="height: 620px; overflow: auto;">
        <ul class="comments-list" style="list-style: none;">
            @if (Model.CommentsList == null || Model.CommentsList.Count() == 0)
            {
            <div class="no-comments" align="center">
                <h3 style="color: gray;">@Resource.CommentsNot </h3>
            </div>
            }
            else
            {
                foreach (var comment in Model.CommentsList)
                {
                <li>
                    <div class="commenter-avatar">
                        <img src=@Url.Content($"/Content/images/avatars/{comment.Author.Avatar}") alt="avatar" />
                    </div>
                    <div class="commenter-name">@comment.Author.FirstName @comment.Author.LastName </div>
                    <div class="comment-date">@comment.DateCreate</div>
                    <div class="clearfix"></div>
                    <div class="comment-text">@comment.Text</div>
                </li>
                }

            }
        </ul>
    </div>
</div>

ScrumTracker/WebSite/Views/Issue/_IssueInfoPartial.cshtml
@using DataLayer.Entities
@model WebSite.Models.Issue.IssueInfoModel
@{
    ViewBag.Title = "_IssueInfoPartial";
}

<div id="issue-tabs">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#issue-tab-1">@Resources.Resource.IssueInfo</a></li>
        <li><a data-toggle="tab" href="#issue-tab-2">@Resources.Resource.IssueComments</a></li>
        <li><a data-toggle="tab" href="#issue-tab-3">@Resources.Resource.TimeTracking</a></li>
    </ul>
    <div class="tab-content">
        <div id="issue-tab-1" class="tab-pane fade in active">
            @*<div class="issue-info-wrapper panel panel-primary">*@
                <div class="issue-info-wrapper">
                    @Html.Partial("~/Views/Issue/_IssueDataPartial.cshtml")
                </div>
        </div>
        <div id="issue-tab-2" class="tab-pane fade">
            <div class="panel panel-primary issue-info-wrapper">
           
                @Html.Partial("~/Views/Issue/_IssueCommentsPartial.cshtml")
            </div>
        </div>
        <div id="issue-tab-3" class="tab-pane fade">
            <div class="panel panel-primary issue-info-wrapper">
                @Html.Partial("~/Views/Issue/_IssueTimeTrackingPartial.cshtml")
            </div>
        </div>
    </div>
</div>
<input type="hidden" value="@ViewBag.Permission.ToString().ToLower()" id="viewbag-issue-permission" />

ScrumTracker/WebSite/Views/Issue/_ListIssuesPartial.cshtml
@using PagedList
@using PagedList.Mvc
@model WebSite.Models.Issue.IssueModel
@{
    ViewBag.Title = "_ListIssuesPartial";
}


<div class="row headings-for-issues">
    <h5 class="col-md-3">@Resources.Resource.IssuePriority</h5>
    <h5 class="col-md-3">@Resources.Resource.IssueState</h5>
    <h5 class="col-md-3">@Resources.Resource.IssueType</h5>
    <h5 class="col-md-3">@Resources.Resource.Created</h5>
</div>
<ul id="issue-list">
    @foreach (var issue in Model.Issues)
    {
    <li class="issue-item" data-id="@issue.Id">
        <div class="row issue-list-item-info">
            <div class="col-md-11 issue-list-item-name">
                <p >
                    <a href="#" data-id="@issue.Id" type="button"><span class="@(issue.State.Name == "Fixed" ||issue.State.Name == "Verified" ? "task-ended" : "")">@issue.Project.Code-@issue.Number </span> @issue.Name</a>
                </p>
            </div>
            <div class="col-md-1 issue-list-delete">
                <div class="delete-issue">
                    @if (ViewBag.Permission)
                {
                <a href="@Url.Action("DeleteIssueInfo", "Issue", new {id = issue.Id})" class="issue-delete"><i class="fa  fa-times"></i></a>
                    }
                </div>
            </div>
        </div>
        <div class="row issue-list-item-info">
            <div class="col-md-3 issue-list-priority-name"> @Html.DisplayFor(model => issue.Priority.Name) </div>
            <div class="col-md-3 issue-list-state-name"> @Html.DisplayFor(model => issue.State.Name) </div>
            <div class="col-md-3 issue-list-type-name"> @Html.DisplayFor(model => issue.IssueType.Name) </div>
            <div class="col-md-3 issue-list-sprint-name">@issue.DateCreate.ToShortDateString()</div>
            @*<div class="col-md-1 issue-list-delete">
                    <div class="delete-issue">
                        @if (ViewBag.Permission)
                        {
                            <a href="@Url.Action("DeleteIssueInfo", "Issue", new {id = issue.Id})" class="issue-delete"><i class="fa  fa-times"></i></a>
                        }
                    </div>
                </div>*@
        </div>
        <input type="hidden" class="issue-id" value="@issue.Id" />
    </li>
    }
</ul>



<input type="hidden" value="@ViewBag.IssueFilter" id="viewbagIssueFilter" />
<input type="hidden" value="@ViewBag.IssuePage" id="viewbagIssuePage" />
<input type="hidden" value="@ViewBag.ProjectId" id="viewbagIssueProject" />
<input type="hidden" value="@ViewBag.IssueSortFilter" id="viewbagIssueSortFilter" />



<div class="text-center">
    @if (Model.Issues.PageCount > 1)
    {
    @Html.PagedListPager((IPagedList)Model.Issues,
        page => Url.Action("SearchIssues", new
        {
            page,
            term = ViewBag.IssueFilter,
            projectId = ViewBag.ProjectId,
            sortFilter = ViewBag.IssueSortFilter
        }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.PageNumbersOnly,
            new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "Get",
                UpdateTargetId = "issues"
            }))

    }
</div>