ScrumTracker/WebSite/Controllers/HomeController.cs
using System.Web.Mvc;
using BusinessLayer.Contracts.Interfaces;
using WebSite.Models;
using System;
using System.Collections.Generic;
using WebSite.Util.Filters;
using System.Runtime.InteropServices;
using System.Linq;

namespace WebSite.Controllers
{
    [RequireHttps]
    [Authorize]
    
    public class HomeController : BaseController
    {
        private readonly IManagerProject mngrProject;
        private readonly IManagerTeam mngrTeam;
        private readonly IManagerSprint mngrSprint;
        private readonly IManagerIssue mngrIssue;

        public HomeController(IManagerProject projectManager, IManagerTeam teamManager, IManagerSprint sprintManager, IManagerIssue issueManager)
        {
            mngrProject = projectManager;
            mngrTeam = teamManager;
            mngrSprint = sprintManager;
            mngrIssue = issueManager;
        }

        public ActionResult Index()
        {

            List<DashBoardView> vm = new List<DashBoardView>();

            var teamsList = mngrTeam.GetUsersTeams(CurrentUserId);
      
            var projectList = mngrProject.GetUsersProject(Guid.Parse(CurrentUserId)).Where(x=>x.StateProject.Name == "Open");

            if (projectList != null)
            {
                foreach (var project in projectList)
                {                   

                    var sprints = mngrSprint.GetSprintsByProjectId(project.Id);

                    if (sprints != null)
                    {
                        foreach (var sprint in sprints.Where(x => x.State == 1))
                        {
                            DashBoardView item = new DashBoardView();
                            item.ProjectName = project.Name;
                            item.ProjectId = project.Id;
                            item.SprintId = sprint.Id;
                            item.SprintName = sprint.Name;
                            item.EndDate = sprint.DateEnd;
                            item.IssueList = mngrIssue.GetAllIssuesByProjectId(project.Id)
                                                .Where(x => x.IssueType.Name.Equals("Task"));
                                               // .OrderBy(x=>x.);                            

                            vm.Add(item);
                        }
                    }
                }
            }

            return View(vm);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ScrumTracker/WebSite/Controllers/SprintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BusinessLayer.Contracts.Interfaces;
using DTO.Entities;
using WebSite.Models.Issue;
using WebSite.Models.Sprint;

namespace WebSite.Controllers
{
    public enum stateSprint { New, Active, Closed }

    [Authorize]
    public class SprintController : BaseController
    {
        private readonly IManagerProject _projectManager;
        private readonly IManagerSprint _sprintManager;
        private readonly IManagerIssue _issueManager;

        public SprintController(IManagerProject projectManager, IManagerSprint sprintManager, IManagerIssue issueManager)
        {
            _projectManager = projectManager;
            _sprintManager = sprintManager;
            _issueManager = issueManager;
        }

        public ActionResult Index(Guid? id)
        {
            ViewBag.IsAdmin = HttpContext.User.IsInRole("Admin");
            var listProjects = ViewBag.IsAdmin ? _projectManager.GetProjectByDepartmentId(CurrentUser.Department.Id)
                                               : _projectManager.GetUsersProject(Guid.Parse(CurrentUserId));
            ViewBag.ListProjects = listProjects != null ? new SelectList(listProjects.ToArray(), "Id", "Name", id) : null;
            return View();
        }

        public JsonResult AccessByCreateSprint(Guid? id)
        {
            var access = false;
            if (!HttpContext.User.IsInRole("Admin"))
            {
                var team = _projectManager.GetProjectById(id).Team;
                if (team != null)
                {
                    if (team.UserTeamPositions.FirstOrDefault(
                        x => x.UserId == CurrentUserId && (x.Position.Name == "Project Manager"
                                                           || x.Position.Name == "Scrum Master")) != null)
                    {
                        access = true;
                    }
                }
            }
            else
            {
                access = true;
            }
            return Json(access, JsonRequestBehavior.AllowGet);
        }

        // GET: Sprint
        public ActionResult GetSprintsByProjectId(Guid? id)
        {
            if (id == null)
                return PartialView("_GetSprintsByProjectId", null);

            ViewBag.Access = AccessByCreateSprint(id).Data;
            IEnumerable<SprintDto> sprints = null;
            try
            {
                sprints = _sprintManager.GetSprintsByProjectId(id);
                sprints = sprints?.OrderByDescending(x => x.DateBegin);
            }
            catch (Exception e)
            {
                Response.Write(e.Message);
            }
            return sprints == null ? PartialView("_GetSprintsByProjectId", null)
                   : PartialView("_GetSprintsByProjectId", MappingDtoToModels(sprints));
        }

        public ActionResult GetIssuesBySprintId(Guid? sprintId)
        {
            var issues = _issueManager.GetIssuesBySprintId(sprintId).Where(x => x.ParentIssueId == null);
            issues = issues?.OrderBy(x => x.Number);
            if (issues.Count() != 0)
            {
                var issuesModel = MappingIssueDtoToModel(issues);
                return PartialView("_GetIssuesBySprintId", issuesModel);
            }
            return PartialView("_GetIssuesBySprintId", null);
        }

        public ActionResult MoveIssueInSprint(Guid? sprintId, Guid issueId)
        {
            var issue = _issueManager.GetIssueById(issueId);
            if (issue.SprintId != sprintId)
            {
                issue.SprintId = sprintId;
                _issueManager.UpdateIssue(issue);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MoveIssueInBoard(Guid issueId, string nameState)
        {
            var issue = _issueManager.GetIssueById(issueId);
            var state = _issueManager.GetStateByName(nameState);
            if (state != null)
            {
                issue.State = state;
                issue.StateId = state.Id;
                _issueManager.UpdateIssue(issue);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult StartSprint(Guid id)
        {
            var errorActive = 0; // error activing sprint - when project has already contained active sprint
            var errorClosed = 0; // error closing sprint - when sprint contains not fixed issues
            var sprint = _sprintManager.GetSprintById(id);
            try
            {
                if (sprint.State == (int)stateSprint.New)
                {
                    var checkActiveSprint = _sprintManager.GetSprintsByProjectId(sprint.ProjectId)
                                            .FirstOrDefault(a => a.Id != id && a.State == (int)stateSprint.Active);
                    if (checkActiveSprint == null)
                    {
                        sprint.State = (int)stateSprint.Active;
                        _sprintManager.UpdateSprint(sprint);
                    }
                    else
                    {
                        errorActive = 1;
                    }
                }
                else
                {
                    var countIssues = _issueManager.GetIssuesBySprintId(id).Count(x => x.State.Name != "Fixed");
                    if (countIssues == 0)
                    {
                        sprint.State = (int)stateSprint.Closed;
                        _sprintManager.UpdateSprint(sprint);
                    }
                    else
                    {
                        errorClosed = 1;
                    }
                }
            }
            catch
            {
                // ignored
            }
            var list = new List<int> { sprint.State, errorActive, errorClosed };
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CountIssues(Guid sprintId)
        {
            var countIssues = new List<int>();
            var sprint = MappingDtoToModels(_sprintManager.GetSprintById(sprintId));
            countIssues.Add(sprint.CountAllIssues);
            countIssues.Add(sprint.CountTaskOpen);
            countIssues.Add(sprint.CountTaskInProgess);
            countIssues.Add(sprint.CountTaskFixed);
            countIssues.Add(sprint.CountTaskVerified);            
            return Json(countIssues, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShowPlanning(Guid sprintId, Guid projectId)
        {
            var backlogProject = _issueManager.GetAllIssuesByProjectId(projectId)
                                .Where(x => x.State.Name != "Fixed" && x.Sprint == null);
            var backlogSprint = _issueManager.GetIssuesBySprintId(sprintId);
            backlogProject = backlogProject?.OrderBy(x => x.Number);
            backlogSprint = backlogSprint?.OrderBy(x => x.Number);
            var planning = new SprintBacklogModel()
            {
                SprintId = sprintId,
                Backlog = MappingIssueDtoToModel(backlogProject),
                Sprint = MappingIssueDtoToModel(backlogSprint)
            };
            return PartialView(planning);
        }

        public ActionResult ShowAgileBoard(Guid sprintId, Guid issueId)
        {
            SprintBoardModel board;
            var issue = _issueManager.GetIssueById(issueId);
            if (issue.IssueType.Name == "Task" || issue.IssueType.Name == "Bug")
            {
                IList<IssueDto> list = new List<IssueDto>(); 
                list.Add(issue);
                board = new SprintBoardModel()
                {
                    SprintId = sprintId,
                    ParentIssueId = null,
                    IsTaskOrBug = true,
                    IssueOpen = MappingIssueDtoToModel(list.Where(x => x.State.Name == "Open")),
                    IssueReopened = MappingIssueDtoToModel(list.Where(x => x.State.Name == "Reopened")),
                    IssueInProgress = MappingIssueDtoToModel(list.Where(x => x.State.Name == "In Progress")),
                    IssueFixed = MappingIssueDtoToModel(list.Where(x => x.State.Name == "Fixed")),
                    IssueVerified = MappingIssueDtoToModel(list.Where(x => x.State.Name == "Verified"))
                }; 
            }
            else
            {
                var allIssues = _issueManager.GetIssuesBySprintId(sprintId).Where(x => x.ParentIssueId == issueId);
                var issueDtos = allIssues as IssueDto[] ?? allIssues.ToArray();
                board = new SprintBoardModel()
                {
                    SprintId = sprintId,
                    ParentIssueId = issueId,
                    IsTaskOrBug = false,
                    IssueOpen = MappingIssueDtoToModel(issueDtos.Where(x => x.State.Name == "Open").OrderBy(x => x.Number)),
                    IssueReopened = MappingIssueDtoToModel(issueDtos.Where(x => x.State.Name == "Reopened").OrderBy(x => x.Number)),
                    IssueInProgress = MappingIssueDtoToModel(issueDtos.Where(x => x.State.Name == "In Progress").OrderBy(x => x.Number)),
                    IssueFixed = MappingIssueDtoToModel(issueDtos.Where(x => x.State.Name == "Fixed").OrderBy(x => x.Number)),
                    IssueVerified = MappingIssueDtoToModel(issueDtos.Where(x => x.State.Name == "Verified").OrderBy(x => x.Number))
                };
            }
            return PartialView(board);
        }

        public ActionResult AddIssueInSprint(Guid sprintId, string typeName, Guid? parentIssueId)
        {
            var type = _issueManager.GetTypeByName(typeName);
            var model = new AddIssueModel
            {
                SprintId = sprintId,
                IssueTypeId = type.Id,
                ParentIssueId = parentIssueId
            };
            if (typeName != "Task")

ScrumTracker/WebSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ScrumTracker/WebSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ScrumTracker/WebSite/Views/Home/Index.cshtml
@model IEnumerable<WebSite.Models.DashBoardView>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="margin-top:25px;">

    @{ int i = 0; string chartScript = String.Empty;}

    @if (Model.Count() == 0)
    {

        <div class="no-projects">
            <div>@Resources.Resource.NO_PROJECTS_YET</div>
        </div>

    }
    else {

        foreach (var sprint in Model)
        {

            <div class="row item_@i">
                <div class="col-md-8">
                    <h3>
                        @Html.ActionLink(sprint.SprintName, "Index", "Sprint", new { id = sprint.SprintId }, null)
                        ( @Html.ActionLink(sprint.ProjectName, "FilterProjectsByName", "Project", new { id = sprint.ProjectName }, null) )
                    </h3>
                    <ul class="nav nav-pills">

                        @if (sprint.EndDate < DateTime.Now)
                        {
                            <li class='counter-head label-danger'>
                                <h5>X</h5>
                                <div>past</div>
                                <div>due</div>
                            </li>
                        }
                        else
                        {
                            <li class='counter-head label-primary'>
                                <h5>@Convert.ToInt32((sprint.EndDate.AddDays(1) - @DateTime.Now).TotalDays) </h5>
                                <div>@Resources.Resource.Days</div>
                                <div>@Resources.Resource.Left</div>
                            </li>
                        }
                        <li class="counter-head label-warning">
                            <h5>@sprint.IssueList.Where(x=>x.State.Name == "Open").Count()<br></h5>
                            <div>@Resources.Resource.Task</div>
                            <div>@Resources.Resource.Left</div>
                        </li>

                        <li class="counter-head label-info">
                            <h5>@sprint.IssueList.Where(x => x.State.Name == "In Progress").Count()<br></h5>
                            <div>@Resources.Resource.Task</div>
                            <div>@Resources.Resource.InProgress</div>
                        </li>

                        <li class="counter-head label-success">
                            <h5>@sprint.IssueList.Where(x => x.State.Name == "Fixed").Count()<br></h5>
                            <div>@Resources.Resource.Task</div>
                            <div>@Resources.Resource.Done</div>
                        </li>
                    </ul>
                    <a href="#" onclick="drawBurnDownChart(@i)"><i class="glyphicon glyphicon-alert" ></i>@Resources.Resource.SPRINT_DETAILS</a>
                    <div id="burndownChart_@i"></div>
                </div>
                <div class="col-md-4">
                    <div class="char_@i chart-item"></div>
                </div>
                <hr />
            </div>
            i = i + 1;
        }
        <div id="curve_chart"></div>

        @section scripts{
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <script type="text/javascript">

                function ShowBlockChart(num) {
                    $(".item_" + num).find(".open").removeClass("open").addClass("closed");
                    $(".item_" + num).find(".totalCharts").removeClass("closed").addClass("open");
                    drawBurnDownChart();
                }

                // Load the Visualization API and the piechart package.
                google.charts.load('current', { 'packages': ['corechart','line'] });
                google.charts.setOnLoadCallback(drawChart);




                //   google.charts.setOnLoadCallback(drawBurnDownChart);

                function drawBurnDownChart(num) {
                

                    var data = new google.visualization.DataTable();
                    data.addColumn('number', 'Day');
                    data.addColumn('number', '@Resources.Resource.ACTUAL_BD');
                    data.addColumn('number', '@Resources.Resource.IDEAL_DB');
             

                    data.addRows([
                      [1,  37.8, 80.8],
                      [2,  30.9, 69.5],
                      [3,  25.4,   57],
                      [4,  11.7, 18.8],
                      [5,  11.9, 17.6],
                      [6,   8.8, 13.6],
                      [7,   7.6, 12.3],
                      [8,  12.3, 29.2],
                      [9,  16.9, 42.9],
                      [10, 12.8, 30.9],
                      [11,  5.3,  7.9],
                      [12,  6.6,  8.4],
                      [13,  4.8,  6.3],
                      [14,  4.2,  6.2]
                    ]);

                    var options = {
                        backgroundColor: '#1C1C1C',
                        chart: {
                            color: "#fff",
                            legend: { position: 'none' },
                           
                            bar: { groupWidth: "95%" },
                            legend: { position: "none" },
                        },
                       
                    };

                    var chart = new google.charts.Line(document.getElementById('burndownChart_'+num));

                    chart.draw(data, options);
                }



                // Callback that creates and populates a data table,
                // instantiates the pie chart, passes in the data and
                // draws it.
                function drawChart() {

                    var chrtPlaceholders = document.getElementsByClassName("chart-item");

                    for (var i = 0; i < chrtPlaceholders.length; i++) {

                        var open = $(".item_" + i).find(".label-warning").find("h5").text() / 1;
                        var inProgress = $(".item_" + i).find(".label-info").find("h5").text() / 1;
                        var closed = $(".item_" + i).find(".label-success").find("h5").text() / 1;

                        //var data = google.visualization.arrayToDataTable([
                        //           ['Task', 'Hours per Day'],
                        //           ['Tasks open', open],
                        //           ['Tasks in progress', inProgress],
                        //           ['Tasks done', closed]
                        //                    ]);

                        //var options = {
                        //    color: '#fff',
                        //    legend: { position: 'none' },
                        //    backgroundColor: 'transparent',
                        //    colors: ['#f39c12', '#3498db', '#00bc8c']
                        //};

                        //var chart = new google.visualization.PieChart(document.getElementsByClassName('char_'+i)[0]);
                        //chart.draw(data, options);

                        var data = google.visualization.arrayToDataTable([
                ["Element", "Density", { role: "style" }],
                ["@Resources.Resource.Open", open, "#f39c12"],
                ["@Resources.Resource.InProgress", inProgress, "3498db"],
                ["@Resources.Resource.Done", closed, "00bc8c"],
                        ]);

                        var view = new google.visualization.DataView(data);
                        view.setColumns([0, 1,
                                         {
                                             calc: "stringify",
                                             sourceColumn: 1,
                                             type: "string",
                                             role: "annotation"
                                         },
                                         2]);

                        var options = {

                            hAxis: {
                                textStyle: { color: 'white' },
                            },
                            //vAxis: {
                            //    textStyle: { color: 'red' },
                            //},
                            color: "#fff",
                            legend: { position: 'none' },
                            backgroundColor: 'transparent',
                            bar: { groupWidth: "95%" },
                            legend: { position: "none" },
                        };
                        var chart = new google.visualization.ColumnChart(document.getElementsByClassName('char_' + i)[0]);
                        chart.draw(view, options);
                    }
                }
            </script>
        }
    }
</div>